// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package bot

import (
	context "context"

	core "github.com/ksysoev/make-it-public-tgbot/pkg/core"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function with given fields: ctx, userID
func (_m *MockTokenService) CreateToken(ctx context.Context, userID string) (*core.APIToken, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 *core.APIToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.APIToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.APIToken); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.APIToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenService_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockTokenService_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTokenService_Expecter) CreateToken(ctx interface{}, userID interface{}) *MockTokenService_CreateToken_Call {
	return &MockTokenService_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, userID)}
}

func (_c *MockTokenService_CreateToken_Call) Run(run func(ctx context.Context, userID string)) *MockTokenService_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenService_CreateToken_Call) Return(_a0 *core.APIToken, _a1 error) *MockTokenService_CreateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenService_CreateToken_Call) RunAndReturn(run func(context.Context, string) (*core.APIToken, error)) *MockTokenService_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
