// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	conv "github.com/ksysoev/make-it-public-tgbot/pkg/core/conv"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// AddAPIKey provides a mock function with given fields: ctx, userID, apiKeyID, expiresIn
func (_m *MockUserRepo) AddAPIKey(ctx context.Context, userID string, apiKeyID string, expiresIn time.Duration) error {
	ret := _m.Called(ctx, userID, apiKeyID, expiresIn)

	if len(ret) == 0 {
		panic("no return value specified for AddAPIKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, userID, apiKeyID, expiresIn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_AddAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAPIKey'
type MockUserRepo_AddAPIKey_Call struct {
	*mock.Call
}

// AddAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - apiKeyID string
//   - expiresIn time.Duration
func (_e *MockUserRepo_Expecter) AddAPIKey(ctx interface{}, userID interface{}, apiKeyID interface{}, expiresIn interface{}) *MockUserRepo_AddAPIKey_Call {
	return &MockUserRepo_AddAPIKey_Call{Call: _e.mock.On("AddAPIKey", ctx, userID, apiKeyID, expiresIn)}
}

func (_c *MockUserRepo_AddAPIKey_Call) Run(run func(ctx context.Context, userID string, apiKeyID string, expiresIn time.Duration)) *MockUserRepo_AddAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockUserRepo_AddAPIKey_Call) Return(_a0 error) *MockUserRepo_AddAPIKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_AddAPIKey_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockUserRepo_AddAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConversation provides a mock function with given fields: ctx, conversationID
func (_m *MockUserRepo) DeleteConversation(ctx context.Context, conversationID string) error {
	ret := _m.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConversation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, conversationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_DeleteConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConversation'
type MockUserRepo_DeleteConversation_Call struct {
	*mock.Call
}

// DeleteConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID string
func (_e *MockUserRepo_Expecter) DeleteConversation(ctx interface{}, conversationID interface{}) *MockUserRepo_DeleteConversation_Call {
	return &MockUserRepo_DeleteConversation_Call{Call: _e.mock.On("DeleteConversation", ctx, conversationID)}
}

func (_c *MockUserRepo_DeleteConversation_Call) Run(run func(ctx context.Context, conversationID string)) *MockUserRepo_DeleteConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepo_DeleteConversation_Call) Return(_a0 error) *MockUserRepo_DeleteConversation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_DeleteConversation_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRepo_DeleteConversation_Call {
	_c.Call.Return(run)
	return _c
}

// GetAPIKeys provides a mock function with given fields: ctx, userID
func (_m *MockUserRepo) GetAPIKeys(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAPIKeys")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_GetAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIKeys'
type MockUserRepo_GetAPIKeys_Call struct {
	*mock.Call
}

// GetAPIKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepo_Expecter) GetAPIKeys(ctx interface{}, userID interface{}) *MockUserRepo_GetAPIKeys_Call {
	return &MockUserRepo_GetAPIKeys_Call{Call: _e.mock.On("GetAPIKeys", ctx, userID)}
}

func (_c *MockUserRepo_GetAPIKeys_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepo_GetAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepo_GetAPIKeys_Call) Return(_a0 []string, _a1 error) *MockUserRepo_GetAPIKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_GetAPIKeys_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockUserRepo_GetAPIKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetConversation provides a mock function with given fields: ctx, conversationID
func (_m *MockUserRepo) GetConversation(ctx context.Context, conversationID string) (*conv.Conversation, error) {
	ret := _m.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for GetConversation")
	}

	var r0 *conv.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*conv.Conversation, error)); ok {
		return rf(ctx, conversationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *conv.Conversation); ok {
		r0 = rf(ctx, conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conv.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, conversationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_GetConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConversation'
type MockUserRepo_GetConversation_Call struct {
	*mock.Call
}

// GetConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID string
func (_e *MockUserRepo_Expecter) GetConversation(ctx interface{}, conversationID interface{}) *MockUserRepo_GetConversation_Call {
	return &MockUserRepo_GetConversation_Call{Call: _e.mock.On("GetConversation", ctx, conversationID)}
}

func (_c *MockUserRepo_GetConversation_Call) Run(run func(ctx context.Context, conversationID string)) *MockUserRepo_GetConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepo_GetConversation_Call) Return(_a0 *conv.Conversation, _a1 error) *MockUserRepo_GetConversation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_GetConversation_Call) RunAndReturn(run func(context.Context, string) (*conv.Conversation, error)) *MockUserRepo_GetConversation_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function with given fields: ctx, userID, apiKeyID
func (_m *MockUserRepo) RevokeToken(ctx context.Context, userID string, apiKeyID string) error {
	ret := _m.Called(ctx, userID, apiKeyID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, apiKeyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockUserRepo_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - apiKeyID string
func (_e *MockUserRepo_Expecter) RevokeToken(ctx interface{}, userID interface{}, apiKeyID interface{}) *MockUserRepo_RevokeToken_Call {
	return &MockUserRepo_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, userID, apiKeyID)}
}

func (_c *MockUserRepo_RevokeToken_Call) Run(run func(ctx context.Context, userID string, apiKeyID string)) *MockUserRepo_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepo_RevokeToken_Call) Return(_a0 error) *MockUserRepo_RevokeToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_RevokeToken_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepo_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveConversation provides a mock function with given fields: ctx, conversation
func (_m *MockUserRepo) SaveConversation(ctx context.Context, conversation *conv.Conversation) error {
	ret := _m.Called(ctx, conversation)

	if len(ret) == 0 {
		panic("no return value specified for SaveConversation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *conv.Conversation) error); ok {
		r0 = rf(ctx, conversation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_SaveConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveConversation'
type MockUserRepo_SaveConversation_Call struct {
	*mock.Call
}

// SaveConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - conversation *conv.Conversation
func (_e *MockUserRepo_Expecter) SaveConversation(ctx interface{}, conversation interface{}) *MockUserRepo_SaveConversation_Call {
	return &MockUserRepo_SaveConversation_Call{Call: _e.mock.On("SaveConversation", ctx, conversation)}
}

func (_c *MockUserRepo_SaveConversation_Call) Run(run func(ctx context.Context, conversation *conv.Conversation)) *MockUserRepo_SaveConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*conv.Conversation))
	})
	return _c
}

func (_c *MockUserRepo_SaveConversation_Call) Return(_a0 error) *MockUserRepo_SaveConversation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_SaveConversation_Call) RunAndReturn(run func(context.Context, *conv.Conversation) error) *MockUserRepo_SaveConversation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
