name: Deploy

permissions:
  contents: read

on:
  push:
    tags:
      - v*
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.PORT}}
          script: |
            cd make-it-public
            git pull
            docker compose pull
            export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            export MIT_URL=${{ secrets.MIT_URL }}
            export REPO_REDIS_ADDR=${{ secrets.REPO_REDIS_ADDR }}
            export NETWORK_NAME=${{ env.MIT_NETWORK }}
            docker stack deploy -c docker-compose.yml mitbot